import { Car } from './types';

// Date de test pentru mașini disponibile pentru închiriere
export const availableCars: Car[] = [
  {
    id: '1',
    name: 'Dacia Duster',
    brand: 'Dacia',
    model: 'Duster',
    year: 2023,
    color: '#10B981', // verde
    pricePerDay: 35,
    pricePerWeek: 210,
    pricePerMonth: 800,
    fuelType: 'diesel',
    transmission: 'manual',
    seats: 5,
    doors: 5,
    availableFrom: '2025-04-12T00:00:00Z',
    availableTo: '2025-06-30T00:00:00Z',
    features: ['Aer condiționat', 'Bluetooth', 'GPS', 'Cameră parcare', '4x4'],
    imageUrl: 'https://images.unsplash.com/photo-1606152535877-2026896471bc?q=80&w=1974&auto=format&fit=crop',
    rating: 4.5,
    location: 'București',
    description: 'SUV compact perfect pentru călătorii în afara orașului, cu spațiu generos și consum redus de combustibil.',
    category: 'suv'
  },
  {
    id: '2',
    name: 'Volkswagen Golf',
    brand: 'Volkswagen',
    model: 'Golf',
    year: 2024,
    color: '#3B82F6', // albastru
    pricePerDay: 40,
    pricePerWeek: 240,
    pricePerMonth: 900,
    fuelType: 'gasoline',
    transmission: 'automatic',
    seats: 5,
    doors: 5,
    availableFrom: '2025-04-10T00:00:00Z',
    availableTo: '2025-05-15T00:00:00Z',
    features: ['Aer condiționat', 'Bluetooth', 'Apple CarPlay', 'Android Auto', 'Senzori parcare'],
    imageUrl: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?q=80&w=1974&auto=format&fit=crop',
    rating: 4.8,
    location: 'București',
    description: 'Mașină compactă ideală pentru oraș, cu consum redus și dotări moderne pentru confort și siguranță.',
    category: 'compact'
  },
  {
    id: '3',
    name: 'Mercedes-Benz E-Class',
    brand: 'Mercedes-Benz',
    model: 'E-Class',
    year: 2023,
    color: '#1F2937', // negru
    pricePerDay: 80,
    pricePerWeek: 480,
    pricePerMonth: 1800,
    fuelType: 'hybrid',
    transmission: 'automatic',
    seats: 5,
    doors: 4,
    availableFrom: '2025-04-15T00:00:00Z',
    availableTo: '2025-07-01T00:00:00Z',
    features: ['Piele', 'Climatronic', 'Navigație', 'Scaune încălzite', 'Cameră 360°', 'Pilot automat adaptiv'],
    imageUrl: 'https://images.unsplash.com/photo-1563720223489-b3f32be5f1a8?q=80&w=1974&auto=format&fit=crop',
    rating: 5,
    location: 'București',
    description: 'Sedan de lux pentru călătorii de afaceri sau vacanțe confortabile, cu tehnologie de ultimă generație și finisaje premium.',
    category: 'luxury'
  },
  {
    id: '4',
    name: 'Tesla Model 3',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2024,
    color: '#F9FAFB', // alb
    pricePerDay: 75,
    pricePerWeek: 450,
    pricePerMonth: 1700,
    fuelType: 'electric',
    transmission: 'automatic',
    seats: 5,
    doors: 4,
    availableFrom: '2025-04-11T00:00:00Z',
    availableTo: '2025-06-20T00:00:00Z',
    features: ['Autopilot', 'Ecran touch 15"', 'Autonomie 500km', 'Supercharger', 'Camere de securitate'],
    imageUrl: 'https://images.unsplash.com/photo-1619400989250-fadd1dfd1512?q=80&w=1965&auto=format&fit=crop',
    rating: 4.9,
    location: 'București',
    description: 'Mașină 100% electrică cu autonomie mare și tehnologie avansată, perfectă pentru cei care preferă transportul eco-friendly.',
    category: 'luxury'
  },
  {
    id: '5',
    name: 'Renault Clio',
    brand: 'Renault',
    model: 'Clio',
    year: 2023,
    color: '#EF4444', // roșu
    pricePerDay: 30,
    pricePerWeek: 180,
    pricePerMonth: 700,
    fuelType: 'gasoline',
    transmission: 'manual',
    seats: 5,
    doors: 5,
    availableFrom: '2025-04-10T00:00:00Z',
    availableTo: '2025-08-01T00:00:00Z',
    features: ['Aer condiționat', 'Bluetooth', 'USB', 'Consum redus', 'Ușor de parcat'],
    imageUrl: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?q=80&w=1974&auto=format&fit=crop',
    rating: 4.3,
    location: 'București',
    description: 'Mașină economică ideală pentru oraș și deplasări scurte, cu consum redus și manevrabilitate excelentă.',
    category: 'economy'
  },
  {
    id: '6',
    name: 'Toyota RAV4',
    brand: 'Toyota',
    model: 'RAV4',
    year: 2024,
    color: '#6B7280', // gri
    pricePerDay: 60,
    pricePerWeek: 360,
    pricePerMonth: 1400,
    fuelType: 'hybrid',
    transmission: 'automatic',
    seats: 5,
    doors: 5,
    availableFrom: '2025-04-12T00:00:00Z',
    availableTo: '2025-07-15T00:00:00Z',
    features: ['Cameră 360°', 'Navigație', 'Tracțiune 4x4', 'Portbagaj spațios', 'Safety Sense 2.0'],
    imageUrl: 'https://images.unsplash.com/photo-1600861195091-690c92f1d2cc?q=80&w=1980&auto=format&fit=crop',
    rating: 4.7,
    location: 'București',
    description: 'SUV hibrid fiabil cu consum redus, spațios și potrivit atât pentru oraș cât și pentru călătorii în afara orașului.',
    category: 'suv'
  },
  {
    id: '7',
    name: 'Audi A5 Sportback',
    brand: 'Audi',
    model: 'A5 Sportback',
    year: 2023,
    color: '#000000', // negru
    pricePerDay: 70,
    pricePerWeek: 420,
    pricePerMonth: 1600,
    fuelType: 'diesel',
    transmission: 'automatic',
    seats: 5,
    doors: 5,
    availableFrom: '2025-04-10T00:00:00Z',
    availableTo: '2025-06-15T00:00:00Z',
    features: ['Piele', 'Climatronic', 'Bang & Olufsen Audio', 'LED Matrix', 'Virtual Cockpit'],
    imageUrl: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?q=80&w=1969&auto=format&fit=crop',
    rating: 4.8,
    location: 'București',
    description: 'Sportback elegant cu design atrăgător și performanțe dinamice, ideal pentru călătorii de afaceri și vacanțe luxoase.',
    category: 'luxury'
  },
  {
    id: '8',
    name: 'BMW X5',
    brand: 'BMW',
    model: 'X5',
    year: 2024,
    color: '#FFFFFF', // alb
    pricePerDay: 85,
    pricePerWeek: 510,
    pricePerMonth: 1950,
    fuelType: 'hybrid',
    transmission: 'automatic',
    seats: 5,
    doors: 5,
    availableFrom: '2025-04-20T00:00:00Z',
    availableTo: '2025-07-20T00:00:00Z',
    features: ['Piele Nappa', 'Panoramic', 'Harman Kardon', 'Laser Light', 'Asistent șofer'],
    imageUrl: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=1964&auto=format&fit=crop',
    rating: 4.9,
    location: 'București',
    description: 'SUV premium german care îmbină luxul și performanța cu un spațiu interior generos și tehnologie de vârf.',
    category: 'suv'
  }
];
